# Generated by Django 4.2.14 on 2026-08-28 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(help_text='凭据名称', max_length=64, verbose_name='凭据名称')),
                ('username', models.CharField(default='root', help_text='登录用户名', max_length=64, verbose_name='用户名')),
                ('auth_type', models.CharField(choices=[('password', '密码'), ('private_key', '私钥')], default='password', help_text='认证类型', max_length=20, verbose_name='认证类型')),
                ('password', models.TextField(blank=True, help_text='密码密文', null=True, verbose_name='密码(密文)')),
                ('private_key', models.TextField(blank=True, help_text='私钥密文', null=True, verbose_name='私钥(密文)')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('server', models.ForeignKey(blank=True, db_constraint=False, help_text='关联到具体服务器，留空为通用凭据', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.server', verbose_name='关联服务器')),
            ],
            options={
                'verbose_name': '凭据',
                'verbose_name_plural': '凭据',
                'db_table': 'bastion_credential',
            },
        ),
        migrations.CreateModel(
            name='SessionRecord',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('username', models.CharField(blank=True, help_text='实际登录用户名', max_length=64, null=True, verbose_name='登录用户名')),
                ('ip', models.CharField(blank=True, help_text='目标服务器IP', max_length=64, null=True, verbose_name='目标IP')),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='开始时间', verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, help_text='结束时间', null=True, verbose_name='结束时间')),
                ('duration', models.IntegerField(blank=True, default=0, help_text='持续时长', null=True, verbose_name='持续时长(秒)')),
                ('status', models.CharField(choices=[('active', '进行中'), ('closed', '已结束')], default='active', help_text='状态', max_length=20, verbose_name='状态')),
                ('recording', models.CharField(blank=True, help_text='asciinema 录像文件路径', max_length=512, null=True, verbose_name='录像文件路径')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('credential', models.ForeignKey(blank=True, db_constraint=False, help_text='使用的凭据', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bastion.credential', verbose_name='使用凭据')),
                ('server', models.ForeignKey(blank=True, db_constraint=False, help_text='目标服务器', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.server', verbose_name='目标服务器')),
            ],
            options={
                'verbose_name': '会话记录',
                'verbose_name_plural': '会话记录',
                'db_table': 'bastion_session',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('command', models.TextField(help_text='执行的命令', verbose_name='命令')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='执行时间', verbose_name='执行时间')),
                ('is_dangerous', models.BooleanField(default=False, help_text='是否高危命令', verbose_name='高危命令')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('session', models.ForeignKey(db_constraint=False, help_text='所属会话', on_delete=django.db.models.deletion.CASCADE, to='bastion.sessionrecord', verbose_name='会话')),
            ],
            options={
                'verbose_name': '命令审计',
                'verbose_name_plural': '命令审计',
                'db_table': 'bastion_command_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
