# Generated by Django 4.2.14 on 2026-08-31 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmdb', '0001_initial'),
        ('bastion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandDispatch',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(help_text='任务名称', max_length=128, verbose_name='任务名称')),
                ('command', models.TextField(help_text='在每台目标上执行的命令', verbose_name='命令')),
                ('targets', models.JSONField(blank=True, default=list, help_text='JSON 数组：[{"server_id":1,"label":"...","ip":"x.x.x.x"}, ...]', verbose_name='目标列表')),
                ('timeout', models.IntegerField(default=30, help_text='每台目标执行超时秒数', verbose_name='单台超时(秒)')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '全部成功'), ('partial', '部分失败'), ('failed', '全部失败')], default='pending', help_text='任务状态', max_length=20, verbose_name='状态')),
                ('total', models.IntegerField(default=0, help_text='目标总数', verbose_name='目标数')),
                ('success_count', models.IntegerField(default=0, help_text='执行成功数', verbose_name='成功数')),
                ('failed_count', models.IntegerField(default=0, help_text='执行失败数', verbose_name='失败数')),
                ('started_at', models.DateTimeField(blank=True, help_text='实际开始执行时间', null=True, verbose_name='开始执行时间')),
                ('finished_at', models.DateTimeField(blank=True, help_text='执行完成时间', null=True, verbose_name='结束时间')),
                ('last_error', models.TextField(blank=True, help_text='执行异常信息', null=True, verbose_name='最近错误')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('credential', models.ForeignKey(blank=True, db_constraint=False, help_text='任务级统一凭据', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bastion.credential', verbose_name='凭据')),
            ],
            options={
                'verbose_name': '命令下发',
                'verbose_name_plural': '命令下发',
                'db_table': 'bastion_command_dispatch',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='CommandDispatchItem',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('label', models.CharField(blank=True, help_text='目标显示名', max_length=128, verbose_name='目标标签')),
                ('ip', models.CharField(help_text='实际连接 IP', max_length=64, verbose_name='目标IP')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('success', '成功'), ('failed', '失败'), ('timeout', '超时')], default='pending', help_text='执行状态', max_length=20, verbose_name='状态')),
                ('stdout', models.TextField(blank=True, help_text='命令标准输出', verbose_name='标准输出')),
                ('stderr', models.TextField(blank=True, help_text='命令标准错误', verbose_name='标准错误')),
                ('exit_code', models.IntegerField(blank=True, help_text='命令退出码', null=True, verbose_name='退出码')),
                ('duration', models.FloatField(blank=True, help_text='执行耗时', null=True, verbose_name='耗时(秒)')),
                ('error', models.CharField(blank=True, help_text='连接/认证/超时错误', max_length=512, verbose_name='错误信息')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('dispatch', models.ForeignKey(db_constraint=False, help_text='所属下发任务', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bastion.commanddispatch', verbose_name='下发任务')),
                ('server', models.ForeignKey(blank=True, db_constraint=False, help_text='CMDB 来源的目标', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.server', verbose_name='目标服务器')),
            ],
            options={
                'verbose_name': '命令下发结果',
                'verbose_name_plural': '命令下发结果',
                'db_table': 'bastion_command_dispatch_item',
                'ordering': ['id'],
            },
        ),
    ]
