# Generated by Django 4.2.14 on 2026-08-31 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bastion', '0002_commanddispatch_commanddispatchitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='commanddispatch',
            name='max_workers',
            field=models.IntegerField(default=10, help_text='同时执行的目标数（1-50）', verbose_name='并发数'),
        ),
        migrations.AddField(
            model_name='commandlog',
            name='dispatch',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='所属命令下发任务', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_logs', to='bastion.commanddispatch', verbose_name='下发任务'),
        ),
        migrations.AddField(
            model_name='commandlog',
            name='ip',
            field=models.CharField(blank=True, help_text='目标服务器IP（命令下发时记录）', max_length=64, null=True, verbose_name='目标IP'),
        ),
        migrations.AddField(
            model_name='commandlog',
            name='source',
            field=models.CharField(choices=[('session', '交互会话'), ('dispatch', '命令下发')], default='session', help_text='命令来源', max_length=20, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='commandlog',
            name='session',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='所属会话（交互会话）', null=True, on_delete=django.db.models.deletion.CASCADE, to='bastion.sessionrecord', verbose_name='会话'),
        ),
    ]
