# Generated by Django 4.2.14 on 2026-08-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bastion', '0003_commanddispatch_max_workers_commandlog_dispatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commanddispatchitem',
            name='ssh_port',
            field=models.IntegerField(default=22, help_text='SSH 连接端口', verbose_name='SSH端口'),
        ),
    ]
