# Generated by Django 4.2.14 on 2026-08-28 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLine',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(help_text='业务线名称', max_length=64, verbose_name='业务线名称')),
                ('code', models.CharField(blank=True, help_text='业务线编码', max_length=32, null=True, verbose_name='业务线编码')),
                ('owner', models.CharField(blank=True, help_text='负责人', max_length=64, null=True, verbose_name='负责人')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('status', models.IntegerField(choices=[(1, '启用'), (0, '停用')], default=1, help_text='状态', verbose_name='状态')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '业务线',
                'verbose_name_plural': '业务线',
                'db_table': 'cmdb_business_line',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(help_text='环境名称', max_length=64, verbose_name='环境名称')),
                ('code', models.CharField(blank=True, help_text='环境编码', max_length=32, null=True, verbose_name='环境编码')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('status', models.IntegerField(choices=[(1, '启用'), (0, '停用')], default=1, help_text='状态', verbose_name='状态')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '环境',
                'verbose_name_plural': '环境',
                'db_table': 'cmdb_environment',
            },
        ),
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(help_text='机房名称', max_length=64, verbose_name='机房名称')),
                ('code', models.CharField(blank=True, help_text='机房编码', max_length=32, null=True, verbose_name='机房编码')),
                ('location', models.CharField(blank=True, help_text='机房位置', max_length=128, null=True, verbose_name='位置')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('status', models.IntegerField(choices=[(1, '启用'), (0, '停用')], default=1, help_text='状态', verbose_name='状态')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '机房',
                'verbose_name_plural': '机房',
                'db_table': 'cmdb_idc',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('hostname', models.CharField(help_text='主机名', max_length=64, verbose_name='主机名')),
                ('ip', models.CharField(db_index=True, help_text='主管理IP（堡垒机连接用）', max_length=64, verbose_name='主管理IP')),
                ('extra_ips', models.CharField(blank=True, help_text='多网卡时的其他内网IP，逗号分隔', max_length=255, null=True, verbose_name='其他内网IP')),
                ('os', models.CharField(blank=True, help_text='操作系统', max_length=128, null=True, verbose_name='操作系统')),
                ('cpu', models.IntegerField(blank=True, default=0, help_text='CPU核数', null=True, verbose_name='CPU核数')),
                ('memory', models.IntegerField(blank=True, default=0, help_text='内存大小(GB)', null=True, verbose_name='内存(GB)')),
                ('disk', models.CharField(blank=True, help_text='磁盘信息', max_length=255, null=True, verbose_name='磁盘')),
                ('deploy_content', models.CharField(blank=True, help_text='部署的应用/服务，如 nginx / mysql', max_length=255, null=True, verbose_name='部署内容')),
                ('serial_number', models.CharField(blank=True, help_text='设备序列号', max_length=64, null=True, verbose_name='设备序列号')),
                ('purchase_date', models.DateField(blank=True, help_text='采购日期', null=True, verbose_name='采购日期')),
                ('warranty_expiry', models.DateField(blank=True, help_text='维保到期时间', null=True, verbose_name='维保到期')),
                ('ssh_port', models.IntegerField(default=22, help_text='SSH端口', verbose_name='SSH端口')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('maintenance', '维护中'), ('offline_shelf', '已下架')], default='online', help_text='状态', max_length=20, verbose_name='状态')),
                ('tags', models.CharField(blank=True, help_text='标签，逗号分隔', max_length=255, null=True, verbose_name='标签')),
                ('business_line', models.ForeignKey(blank=True, db_constraint=False, help_text='所属业务线', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.businessline', verbose_name='业务线')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('environment', models.ForeignKey(blank=True, db_constraint=False, help_text='所属环境', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.environment', verbose_name='环境')),
                ('idc', models.ForeignKey(blank=True, db_constraint=False, help_text='所属机房', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.idc', verbose_name='机房')),
            ],
            options={
                'verbose_name': '服务器',
                'verbose_name_plural': '服务器',
                'db_table': 'cmdb_server',
                'ordering': ['-create_datetime'],
            },
        ),
    ]
