# Generated by Django 4.2.14 on 2026-09-19 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0002_menu_name_en_menu_name_zh_tw_menubutton_name_en_and_more'),
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerGrant',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('level', models.CharField(choices=[('read', '只读'), ('write', '可操作')], default='read', help_text='只读=仅可查看；可操作=可查看并下发命令/Web SSH', max_length=8, verbose_name='授权级别')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('role', models.ForeignKey(blank=True, db_constraint=False, help_text='授予该角色的全体用户；与「授权用户」至少填一个', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_grants', to='system.role', verbose_name='授权角色')),
                ('server', models.ForeignKey(db_constraint=False, help_text='被授权的服务器资产', on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='cmdb.server', verbose_name='服务器')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='授予该用户本人；与「授权角色」至少填一个', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_grants', to=settings.AUTH_USER_MODEL, verbose_name='授权用户')),
            ],
            options={
                'verbose_name': '服务器资产授权',
                'verbose_name_plural': '服务器资产授权',
                'db_table': 'cmdb_server_grant',
                'ordering': ['server_id', 'id'],
                'indexes': [models.Index(fields=['role'], name='cmdb_grant_role_idx'), models.Index(fields=['user'], name='cmdb_grant_user_idx')],
            },
        ),
    ]
