# Generated by Django 4.2.14 on 2026-09-11 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_menu_name_en_menu_name_zh_tw_menubutton_name_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jenkins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenkinsRolePermission',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('allowed_paths', models.JSONField(blank=True, default=list, help_text='JSON 数组，如 ["dev/","pre/","test/"]；空数组=全部', verbose_name='允许路径前缀')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('role', models.ForeignKey(db_constraint=False, help_text='可见性角色', on_delete=django.db.models.deletion.CASCADE, to='system.role', verbose_name='角色')),
                ('server', models.ForeignKey(db_constraint=False, help_text='关联的 Jenkins 服务器', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='jenkins.jenkinsserver', verbose_name='Jenkins 服务器')),
            ],
            options={
                'verbose_name': 'Jenkins 角色权限',
                'verbose_name_plural': 'Jenkins 角色权限',
                'db_table': 'jenkins_role_permission',
                'ordering': ['id'],
            },
        ),
    ]
