# Generated by Django 4.2.14 on 2026-08-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_add_users_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name_en',
            field=models.CharField(blank=True, help_text='菜单名称(English)', max_length=64, null=True, verbose_name='菜单名称(English)'),
        ),
        migrations.AddField(
            model_name='menu',
            name='name_zh_tw',
            field=models.CharField(blank=True, help_text='菜单名称(繁體中文)', max_length=64, null=True, verbose_name='菜单名称(繁體中文)'),
        ),
        migrations.AddField(
            model_name='menubutton',
            name='name_en',
            field=models.CharField(blank=True, help_text='名称(English)', max_length=64, null=True, verbose_name='名称(English)'),
        ),
        migrations.AddField(
            model_name='menubutton',
            name='name_zh_tw',
            field=models.CharField(blank=True, help_text='名称(繁體中文)', max_length=64, null=True, verbose_name='名称(繁體中文)'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='title_en',
            field=models.CharField(blank=True, help_text='标题(English)', max_length=50, null=True, verbose_name='标题(English)'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='title_zh_tw',
            field=models.CharField(blank=True, help_text='标题(繁體中文)', max_length=50, null=True, verbose_name='标题(繁體中文)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(help_text='菜单名称(默认语言)', max_length=64, verbose_name='菜单名称(默认)'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='form_item_type',
            field=models.IntegerField(blank=True, choices=[(0, '文本'), (1, '日期时间'), (2, '日期'), (3, '长文本'), (4, '下拉'), (5, '多选'), (6, '单选'), (7, '图片(单张)'), (8, '文件'), (9, '开关'), (10, '数字'), (11, '数组'), (12, '图片(多张)'), (13, '关联表'), (14, '关联表(多选)'), (15, '时间')], default=0, help_text='表单类型', verbose_name='表单类型'),
        ),
    ]
