# Generated by Django 4.2.14 on 2026-09-09 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JenkinsServer',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(help_text='服务器名称', max_length=64, verbose_name='服务器名称')),
                ('url', models.CharField(help_text='如 http://192.168.1.100:8080', max_length=255, verbose_name='Jenkins 地址')),
                ('username', models.CharField(blank=True, default='', help_text='认证用户名（可为空，用匿名）', max_length=64, verbose_name='用户名')),
                ('token', models.TextField(blank=True, help_text='API Token 或密码，加密存储', null=True, verbose_name='API Token/密码(密文)')),
                ('status', models.IntegerField(choices=[(1, '启用'), (0, '停用')], default=1, help_text='状态', verbose_name='状态')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'Jenkins 服务器',
                'verbose_name_plural': 'Jenkins 服务器',
                'db_table': 'jenkins_server',
                'ordering': ['sort', '-create_datetime'],
            },
        ),
    ]
