# Generated by Django 4.2.14 on 2026-09-22 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiProviderConfig',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(help_text='便于识别，如 DeepSeek 官方 / 本地 Ollama', max_length=64, unique=True, verbose_name='配置名称')),
                ('provider_type', models.CharField(choices=[('openai_compat', 'OpenAI 兼容')], default='openai_compat', help_text='当前仅支持 OpenAI 兼容协议', max_length=32, verbose_name='接口类型')),
                ('base_url', models.CharField(help_text='如 https://api.deepseek.com/v1（末尾不要带斜杠）', max_length=255, verbose_name='接口地址')),
                ('model', models.CharField(help_text='如 deepseek-chat / deepseek-reasoner / qwen-plus', max_length=128, verbose_name='模型名称')),
                ('api_key', models.TextField(blank=True, help_text='Fernet 密文；接口不返回明文', null=True, verbose_name='API Key(密文)')),
                ('temperature', models.FloatField(default=0.2, help_text='0~2，运维问答建议 0.1~0.3', verbose_name='温度')),
                ('max_tokens', models.IntegerField(default=2048, help_text='单次回答的最大长度', verbose_name='最大输出 token')),
                ('timeout', models.IntegerField(default=60, help_text='大模型响应慢，建议 60~120', verbose_name='请求超时(秒)')),
                ('enabled', models.BooleanField(default=True, help_text='停用后不参与对话', verbose_name='启用')),
                ('is_default', models.BooleanField(default=False, help_text='「智能问答」默认使用该配置', verbose_name='默认供应商')),
                ('description', models.CharField(blank=True, help_text='备注信息', max_length=255, null=True, verbose_name='备注')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'AI 供应商配置',
                'verbose_name_plural': 'AI 供应商配置',
                'db_table': 'ai_provider_config',
                'ordering': ['-is_default', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AiGuardConfig',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('readonly_mode', models.BooleanField(default=True, help_text='开启后仅允许执行白名单内的只读命令；P0 阶段应保持开启', verbose_name='只读模式')),
                ('allowed_commands', models.TextField(blank=True, default='uptime\nfree\ndf\ndu\nvmstat\niostat\nmpstat\nsar\ntop -bn1\ntop -bn2\nps\npstree\nlsof\nss\nnetstat\nifconfig\nip a\nip r\nip addr\nip route\nip link\nip neigh\nnvidia-smi\nlsblk\nlsmod\nfindmnt\ndmesg\nuname\nhostname\nhostnamectl\ndate\ntimedatectl\nwho\nw\nlast\nlastlog\nwhoami\nid\ncat /proc/loadavg\ncat /proc/meminfo\ncat /proc/uptime\ncat /proc/cpuinfo\ncat /proc/stat\ncat /proc/diskstats\ncat /proc/net/dev\ncat /proc/version\ncat /etc/os-release\ncat /etc/hostname\ncat /etc/hosts\ncat /etc/fstab\ncat /etc/resolv.conf\ngrep\nzgrep\nhead\ntail\nwc\nsort\nuniq\ncut\ntr\njournalctl\nsystemctl status\nsystemctl is-\nsystemctl list-\nsystemctl show\nsystemctl cat\nsystemctl --failed\ndocker ps\ndocker images\ndocker stats\ndocker logs\ndocker inspect\ndocker version\ndocker info\ndocker top\ndocker port\ncrontab -l\ngetent hosts\ndig\nnslookup\nping -c\ntraceroute\n', help_text='一行一条，前缀匹配。不在白名单内的命令一律拒绝', verbose_name='只读命令白名单')),
                ('denied_commands', models.TextField(blank=True, default='rm\nmv\ncp\ndd\nmkfs\nfdisk\nparted\nmkswap\nswapon\nswapoff\nshred\nwipefs\ntruncate\nreboot\nshutdown\npoweroff\nhalt\nkill\nkillall\npkill\nsystemctl start\nsystemctl stop\nsystemctl restart\nsystemctl reload\nsystemctl enable\nsystemctl disable\nsystemctl mask\nsystemctl kill\nsystemctl set-\nsystemctl edit\nsystemctl revert\nsystemctl reset-failed\nsystemctl daemon-reload\nservice\nchmod\nchown\nchattr\nlsattr\nuseradd\nuserdel\nusermod\ngroupadd\ngroupdel\npasswd\nchpasswd\nvisudo\nsudo\nsu\ncrontab -e\ncrontab -r\ncrontab -u\nat\niptables\nip6tables\nnft\nip netns\nip link set\nip addr add\nip addr del\nip route add\nip route del\nfirewall-cmd\nufw\nyum\ndnf\napt\napt-get\nrpm\ndpkg\npip\npip3\nnpm\ndocker rm\ndocker rmi\ndocker stop\ndocker start\ndocker restart\ndocker kill\ndocker exec\ndocker run\ndocker compose\ndocker-compose\ndocker volume\ndocker network\ndocker system\nkubectl\nmount\numount\ntee\nxargs\ncurl\nwget\nnc\nncat\nnetcat\ntelnet\nssh\nscp\nsftp\nrsync\nsocat\npython\npython3\nperl\nruby\nnode\nbash -c\nsh -c\nzsh -c\neval\nexec\nsource\nfind\nawk\nsed -i\nln\nhostnamectl set-\ntimedatectl set-\njournalctl --vacuum\njournalctl --rotate\njournalctl --flush\njournalctl --sync\ndate -s\ndate --set\nsysctl -w\nmodprobe\nrmmod\ninsmod\n', help_text='一行一条，命中即拒绝，优先于白名单', verbose_name='危险命令黑名单')),
                ('denied_paths', models.TextField(blank=True, default='/etc/shadow\n/etc/gshadow\n/etc/passwd\n/etc/sudoers\n/etc/ssh/ssh_host\nid_rsa\nid_dsa\nid_ecdsa\nid_ed25519\n.ssh/\n.aws/\n.azure/\n.kube/\n.gcloud/\n.docker/config.json\n.bash_history\n.zsh_history\n.my.cnf\n.pgpass\n.pg_service.conf\n.netrc\n.htpasswd\ncredentials\n.git-credentials\nbackend/conf/env.py\ndocker-compose.yml\n.env\n', help_text='一行一条，命令中出现即拒绝（防止读到凭据文件）', verbose_name='敏感路径黑名单')),
                ('max_rounds', models.IntegerField(default=12, help_text='Agent 最多调用多少次工具后强制收敛', verbose_name='单会话最大轮次')),
                ('max_servers', models.IntegerField(default=5, help_text='一次工具调用最多并发操作的服务器数量', verbose_name='单轮最大机器数')),
                ('command_timeout', models.IntegerField(default=30, help_text='SSH 命令执行的超时时间', verbose_name='单命令超时(秒)')),
                ('max_workers', models.IntegerField(default=4, help_text='批量执行 SSH 时的线程池大小', verbose_name='并发线程数')),
                ('max_output_chars', models.IntegerField(default=8000, help_text='工具输出回灌给大模型前的截断长度', verbose_name='单次输出字符上限')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'AI 护栏配置',
                'verbose_name_plural': 'AI 护栏配置',
                'db_table': 'ai_guard_config',
            },
        ),
    ]
