# Generated by Django 4.2.14 on 2026-09-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiagent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproviderconfig',
            name='enable_thinking',
            field=models.BooleanField(default=False, help_text='仅对 DeepSeek 系列生效。开启后模型会先输出思考过程（更严谨，但更慢、更耗 token）；关闭时会显式发送 thinking={"type":"disabled"} 跳过思考', verbose_name='深度思考'),
        ),
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='model',
            field=models.CharField(help_text='★ 区分大小写。DeepSeek 现役模型：deepseek-flash（快而省，推荐）／ deepseek-v4-pro（重推理）。deepseek-chat / deepseek-reasoner 已被官方于 2026-07-24 弃用，填了会直接 400', max_length=128, verbose_name='模型名称'),
        ),
    ]
