# Generated by Django 4.2.14 on 2026-09-23 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bastion', '0004_commanddispatchitem_ssh_port'),
        ('cmdb', '0002_servergrant'),
        ('aiagent', '0002_aiproviderconfig_enable_thinking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiChatSession',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('title', models.CharField(blank=True, help_text='取第一条提问的前 40 字，便于在列表里辨认', max_length=128, verbose_name='标题')),
                ('messages', models.JSONField(blank=True, default=list, help_text='OpenAI 格式的消息数组（已脱敏）', verbose_name='消息上下文')),
                ('readonly', models.BooleanField(default=True, verbose_name='只读会话')),
                ('rounds', models.IntegerField(default=0, verbose_name='累计模型轮次')),
                ('tool_count', models.IntegerField(default=0, verbose_name='累计工具调用次数')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='累计消耗 token')),
                ('status', models.CharField(choices=[('active', '进行中'), ('done', '已完成'), ('failed', '失败')], default='active', max_length=20, verbose_name='状态')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='最近错误')),
            ],
            options={
                'verbose_name': 'AI 问答会话',
                'verbose_name_plural': 'AI 问答会话',
                'db_table': 'ai_chat_session',
                'ordering': ['-update_datetime'],
            },
        ),
        migrations.CreateModel(
            name='AiToolCall',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('round_index', models.IntegerField(default=0, verbose_name='第几轮')),
                ('tool_name', models.CharField(max_length=64, verbose_name='工具名')),
                ('server_label', models.CharField(blank=True, max_length=128, verbose_name='目标显示名')),
                ('ip', models.CharField(blank=True, max_length=64, verbose_name='目标IP')),
                ('command', models.TextField(blank=True, verbose_name='命令')),
                ('purpose', models.CharField(blank=True, max_length=255, verbose_name='调用理由')),
                ('status', models.CharField(choices=[('success', '成功'), ('empty', '成功但无输出'), ('failed', '执行失败'), ('rejected', '被护栏拒绝'), ('blocked', '无资产授权'), ('error', '参数或系统错误')], default='success', max_length=20, verbose_name='结果')),
                ('reject_reason', models.CharField(blank=True, max_length=512, verbose_name='拒绝原因')),
                ('exit_code', models.IntegerField(blank=True, null=True, verbose_name='退出码')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='耗时(秒)')),
                ('stdout_excerpt', models.TextField(blank=True, verbose_name='标准输出(脱敏截断)')),
                ('stderr_excerpt', models.TextField(blank=True, verbose_name='标准错误(脱敏截断)')),
                ('desensitized', models.CharField(blank=True, help_text='命中的脱敏规则，如「键值对口令×3」', max_length=255, verbose_name='脱敏命中')),
            ],
            options={
                'verbose_name': 'AI 工具调用台账',
                'verbose_name_plural': 'AI 工具调用台账',
                'db_table': 'ai_tool_call',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AiUsage',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('day', models.DateField(verbose_name='日期')),
                ('rounds', models.IntegerField(default=0, verbose_name='模型调用轮次')),
                ('tokens', models.IntegerField(default=0, verbose_name='消耗 token')),
                ('requests', models.IntegerField(default=0, verbose_name='对话次数')),
            ],
            options={
                'verbose_name': 'AI 每日用量',
                'verbose_name_plural': 'AI 每日用量',
                'db_table': 'ai_usage',
                'ordering': ['-day', '-id'],
            },
        ),
        migrations.AddField(
            model_name='aiguardconfig',
            name='chat_timeout',
            field=models.IntegerField(default=90, help_text='一次提问从开始到放弃的总时长。Agent 会在超时前收敛并给出当前结论。网关的读超时是 600 秒，这里留足余量', verbose_name='单次对话时长上限(秒)'),
        ),
        migrations.AddField(
            model_name='aiguardconfig',
            name='daily_round_limit',
            field=models.IntegerField(default=300, help_text='「模型调用轮次」按人按自然日累计。超出后当天不能再提问（防止刷爆自己的 Key 额度）', verbose_name='每人每日轮次上限'),
        ),
        migrations.AddField(
            model_name='aiguardconfig',
            name='daily_token_limit',
            field=models.IntegerField(default=800000, help_text='按人按自然日累计。一般用不到，作为兜底', verbose_name='每人每日 token 上限'),
        ),
        migrations.AddField(
            model_name='aiguardconfig',
            name='desensitize',
            field=models.BooleanField(default=True, help_text='开启后，命令输出与用户提问在**外发大模型之前**会抹掉凭据类内容（密码、Token、AK/SK、JWT、私钥块、连接串里的口令）。★ 强烈建议保持开启：docker inspect 这类命令会原样回显容器环境变量', verbose_name='外发前自动脱敏'),
        ),
        migrations.AddField(
            model_name='aiguardconfig',
            name='desensitize_keywords',
            field=models.TextField(blank=True, default='', help_text='一行一个，**按子串**匹配（不是正则），命中后替换为 ***。适合加公司域名、内部账号名等。少于 3 个字符会被忽略', verbose_name='自定义脱敏关键词'),
        ),
        migrations.AddField(
            model_name='aiguardconfig',
            name='enabled_tools',
            field=models.BooleanField(default=True, help_text='开启后 AI 才能连服务器排查（仍受只读模式与白名单约束）。关闭后 AI 只能基于 CMDB 已有信息做纯问答，一次 SSH 都不建', verbose_name='允许调用只读工具'),
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='该配置只对归属用户可见可用。用户被删除时配置一并删除（离职即自动清理 Key）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_configs', to=settings.AUTH_USER_MODEL, verbose_name='归属用户'),
        ),
        migrations.AlterField(
            model_name='aiguardconfig',
            name='max_rounds',
            field=models.IntegerField(default=12, help_text='Agent 最多调用多少次工具后强制收敛', verbose_name='单次对话最大轮次'),
        ),
        migrations.AlterField(
            model_name='aiguardconfig',
            name='readonly_mode',
            field=models.BooleanField(default=True, help_text='P0 阶段必须开启：只允许执行白名单内的只读命令。★ 关闭后 AI **完全不执行任何命令**（含只读命令）——因为 P0 没有提供任何写操作工具，关掉它没有更宽松的安全档位可落。这是一个应急刹车，不是「放开权限」的开关', verbose_name='只读模式（命令执行总开关）'),
        ),
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='api_key',
            field=models.TextField(blank=True, help_text='Fernet 密文；接口不返回明文。★ 建议使用你自己的 Key，费用记在你自己的账号上', null=True, verbose_name='API Key(密文)'),
        ),
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='is_default',
            field=models.BooleanField(default=False, help_text='「智能问答」默认使用该配置。同一个用户下只允许一条为默认', verbose_name='我的默认供应商'),
        ),
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='name',
            field=models.CharField(help_text='便于识别，如 我的 DeepSeek。同一用户下不可重名', max_length=64, verbose_name='配置名称'),
        ),
        migrations.AddIndex(
            model_name='aiproviderconfig',
            index=models.Index(fields=['owner'], name='ai_provider_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiproviderconfig',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='ai_provider_owner_name_uniq'),
        ),
        migrations.AddField(
            model_name='aiusage',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='aiusage',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_usages', to=settings.AUTH_USER_MODEL, verbose_name='归属用户'),
        ),
        migrations.AddField(
            model_name='aitoolcall',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='aitoolcall',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='冗余自会话，便于「我的台账」直接按人过滤', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_tool_calls', to=settings.AUTH_USER_MODEL, verbose_name='归属用户'),
        ),
        migrations.AddField(
            model_name='aitoolcall',
            name='server',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_tool_calls', to='cmdb.server', verbose_name='目标服务器'),
        ),
        migrations.AddField(
            model_name='aitoolcall',
            name='session',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='tool_logs', to='aiagent.aichatsession', verbose_name='所属会话'),
        ),
        migrations.AddField(
            model_name='aichatsession',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='aichatsession',
            name='credential',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='本会话所有 SSH 都用这一条凭据（任务级统一凭证，与「命令下发」一致）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_chat_sessions', to='bastion.credential', verbose_name='使用的凭据'),
        ),
        migrations.AddField(
            model_name='aichatsession',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='会话与 Key 一样按人隔离：别人看不到你的提问与命令输出', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='归属用户'),
        ),
        migrations.AddField(
            model_name='aichatsession',
            name='provider',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='会话创建时选定的模型配置；配置被删则本字段置空（问历史时提示重选）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_chat_sessions', to='aiagent.aiproviderconfig', verbose_name='使用的模型配置'),
        ),
        migrations.AddConstraint(
            model_name='aiusage',
            constraint=models.UniqueConstraint(fields=('owner', 'day'), name='ai_usage_owner_day_uniq'),
        ),
        migrations.AddIndex(
            model_name='aitoolcall',
            index=models.Index(fields=['session'], name='ai_toolcall_session_idx'),
        ),
        migrations.AddIndex(
            model_name='aitoolcall',
            index=models.Index(fields=['owner'], name='ai_toolcall_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='aichatsession',
            index=models.Index(fields=['owner'], name='ai_chat_owner_idx'),
        ),
    ]
