# Generated by Django 4.2.14 on 2026-08-28 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(help_text='告警名称，需唯一', max_length=128, verbose_name='规则名称')),
                ('expr', models.TextField(help_text='触发告警的 PromQL 表达式，如 up == 0', verbose_name='PromQL 表达式')),
                ('duration', models.CharField(default='1m', help_text='条件持续多久才触发，如 30s / 1m / 5m', max_length=16, verbose_name='持续时间')),
                ('severity', models.CharField(choices=[('critical', '严重'), ('warning', '警告'), ('info', '提示')], default='warning', help_text='告警级别', max_length=16, verbose_name='告警级别')),
                ('summary', models.CharField(blank=True, help_text='告警标题摘要', max_length=255, null=True, verbose_name='告警摘要')),
                ('description', models.CharField(blank=True, help_text='告警详细描述', max_length=512, null=True, verbose_name='告警描述')),
                ('enabled', models.BooleanField(default=True, help_text='停用后规则不参与评估', verbose_name='是否启用')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '告警规则',
                'verbose_name_plural': '告警规则',
                'db_table': 'alert_rule',
                'ordering': ['severity', '-create_datetime'],
            },
        ),
    ]
