# Generated by Django 4.2.14 on 2026-08-28 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyChannel',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(help_text='渠道名称', max_length=64, verbose_name='渠道名称')),
                ('type', models.CharField(choices=[('feishu', '飞书'), ('dingtalk', '钉钉'), ('wechat', '企业微信'), ('email', '邮箱')], help_text='渠道类型', max_length=16, verbose_name='渠道类型')),
                ('config', models.JSONField(blank=True, default=dict, help_text='JSON 配置：飞书/钉钉/企微填 {"webhook":"..."}；邮箱填 {"smtp_host":"","smtp_port":465,"username":"","password":"","to_addrs":["..."]}', verbose_name='渠道配置')),
                ('enabled', models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '通知渠道',
                'verbose_name_plural': '通知渠道',
                'db_table': 'alert_channel',
                'ordering': ['type', '-create_datetime'],
            },
        ),
    ]
