# Generated by Django 4.2.14 on 2026-08-28 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alert', '0002_notifychannel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertGroup',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(help_text='群组名称', max_length=64, verbose_name='群组名称')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('enabled', models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用')),
                ('channels', models.ManyToManyField(blank=True, db_constraint=False, help_text='群组包含的通知渠道', related_name='groups', to='alert.notifychannel', verbose_name='通知渠道')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '告警群组',
                'verbose_name_plural': '告警群组',
                'db_table': 'alert_group',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.AddField(
            model_name='alertrule',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='关联告警群组后，触发时只发群组内的渠道；不选则按所有启用渠道发送', null=True, on_delete=django.db.models.deletion.SET_NULL, to='alert.alertgroup', verbose_name='告警群组'),
        ),
    ]
