# Generated by Django 4.2.14 on 2026-08-31 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alert', '0003_alertgroup_alertrule_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifychannel',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON 配置：飞书/企微填 {"webhook":"..."}；钉钉填 {"webhook":"...","secret":"..."}；邮箱填 {"smtp_host":"","smtp_port":465,"username":"","password":"","to_addrs":["..."]}', verbose_name='渠道配置'),
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('fingerprint', models.CharField(db_index=True, help_text='Alertmanager 告警唯一指纹（labels 哈希）', max_length=64, verbose_name='告警指纹')),
                ('alertname', models.CharField(db_index=True, help_text='告警名称（labels.alertname）', max_length=128, verbose_name='告警名称')),
                ('status', models.CharField(choices=[('firing', '告警中'), ('resolved', '已恢复')], default='firing', help_text='告警状态', max_length=16, verbose_name='状态')),
                ('severity', models.CharField(choices=[('critical', '严重'), ('warning', '警告'), ('info', '提示')], default='warning', help_text='告警级别', max_length=16, verbose_name='告警级别')),
                ('instance', models.CharField(blank=True, help_text='触发告警的实例（labels.instance）', max_length=128, null=True, verbose_name='实例')),
                ('summary', models.CharField(blank=True, help_text='告警摘要（annotations.summary）', max_length=512, null=True, verbose_name='告警摘要')),
                ('description', models.CharField(blank=True, help_text='告警描述（annotations.description）', max_length=1024, null=True, verbose_name='告警描述')),
                ('labels', models.JSONField(blank=True, default=dict, help_text='告警完整 labels', verbose_name='标签')),
                ('starts_at', models.DateTimeField(blank=True, help_text='告警开始时间', null=True, verbose_name='开始时间')),
                ('ends_at', models.DateTimeField(blank=True, help_text='告警恢复时间', null=True, verbose_name='恢复时间')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '告警事件',
                'verbose_name_plural': '告警事件',
                'db_table': 'alert_event',
                'ordering': ['-starts_at', '-create_datetime'],
            },
        ),
    ]
