# Generated by Django 4.2.14 on 2026-08-31 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alert', '0004_alter_notifychannel_config_alertevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertTemplate',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(help_text='模板名称，全局唯一', max_length=64, unique=True, verbose_name='模板名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='模板描述')),
                ('body', models.TextField(help_text='可用变量：alertname / severity / status / instance / summary / description / startsAt / endsAt / value / labels', verbose_name='模板内容（Jinja2）')),
                ('variables', models.JSONField(blank=True, default=list, help_text='自动从 body 中提取的变量名（只读）', verbose_name='模板变量')),
                ('is_default', models.BooleanField(default=False, help_text='True 时在没有任何规则模板命中时使用', verbose_name='默认模板')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('rule', models.ForeignKey(blank=True, db_constraint=False, help_text='为空时按 is_default 字段决定是否兜底使用', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='alert.alertrule', verbose_name='关联告警规则')),
            ],
            options={
                'verbose_name': '告警模板',
                'verbose_name_plural': '告警模板',
                'db_table': 'alert_template',
                'ordering': ['-create_datetime'],
            },
        ),
    ]
