# Generated by Django 4.2.14 on 2026-08-31 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0005_alerttemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerttemplate',
            name='rule',
        ),
        migrations.AddField(
            model_name='alertrule',
            name='template',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='触发后使用该模板渲染通知内容；不选则用默认模板（is_default）或内置格式', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='alert.alerttemplate', verbose_name='通知模板'),
        ),
        migrations.AlterField(
            model_name='alerttemplate',
            name='is_default',
            field=models.BooleanField(default=False, help_text='True 时作为兜底模板，未指定模板的规则触发时使用', verbose_name='默认模板'),
        ),
    ]
