# Generated by Django 4.2.14 on 2026-09-30

from django.db import migrations, models


def mark_existing_as_prom(apps, schema_editor):
    """把升级前已存在的规则统一标记为 prom（只纳管、不下发）。

    为什么不是 platform：
      AddField 的 default='platform' 会把存量规则全刷成「平台来源」。这些规则要么是从
      Prometheus 反向同步建档的，要么本来也从没被下发过。一旦标成 platform，用户升级后第一次
      点「同步规则」就会把它们整份写进 devops_rules.yml —— 与 Prometheus 原有规则形成
      「同名、不同文件」的两条独立规则 ⇒ 告警双发。
      所以存量一律先标 prom（行为与升级前完全一致：什么都不下发），用户想让某条规则由平台
      接管时，在页面上把它的「来源」改成「平台」即可。
    """
    AlertRule = apps.get_model("alert", "AlertRule")
    AlertRule.objects.all().update(source="prom")


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0006_remove_alerttemplate_rule_alertrule_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='source',
            field=models.CharField(choices=[('platform', '平台'), ('prom', 'Prometheus')], default='platform', help_text='platform=平台新建，会被下发到 Prometheus；prom=从 Prometheus 反向同步而来，只做纳管展示、不下发（否则会与 Prometheus 原有规则重复触发）', max_length=16, verbose_name='规则来源'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='labels',
            field=models.JSONField(blank=True, default=dict, help_text='追加到 Prometheus 规则 labels 里的键值对，如 {"team":"ops"}；severity 由「级别」字段统一生成，此处填了也会被忽略', verbose_name='附加标签'),
        ),
        migrations.RunPython(mark_existing_as_prom, migrations.RunPython.noop),
    ]
