# Generated by XwOps on 2026-09-23
"""日志采集配置：LogCollectTask（采集任务）+ LogCollectRecord（操作台账）

★ 手写迁移（离线环境没有可用的 Django 来 makemigrations），
  字段与 `log/models.py` 逐条对齐；两边不一致时以 models.py 为准，
  目标机执行 `makemigrations --check --dry-run` 应当**无待生成变更**。

★★ 手写这张表时踩过的坑（2026-09-24 修）：「继承来的字段」也要抄
------------------------------------------------------------------
`CoreModel` 是 **abstract** 基类，Django 会把它的字段**展平**进每个子模型的
`CreateModel.fields` 里 —— 也就是说，**子模型即使一个字都没写，迁移里也必须有**。

· `LogCollectTask.description` 是**显式重写**的 ⇒ 我抄了 ✓
· `LogCollectRecord.description` 是**从 CoreModel 继承**的 ⇒ **我漏抄了** ✗
  ⇒ 线上 `makemigrations --check` 报 `Add field description to logcollectrecord`

CoreModel 的审计字段全集（来自上游 dvadmin/utils/models.py，勿凭记忆写）：
    id / description / creator / modifier / dept_belong_id /
    update_datetime / create_datetime
其中 `description` 的完整参数是
`CharField(max_length=255, verbose_name="描述", null=True, blank=True, help_text="描述")`
—— 与 `LogCollectTask` 里那份**恰好同名同参**，所以只按名字 grep 是查不出来的。

同批还漏了 `task` 外键的 `help_text='所属采集任务'`（模型有、迁移没有）。
两处都不影响运行，**只影响 `makemigrations --check`**，但这一关过不去就
`migrate` 不了 —— 属于"必炸"级别。离线门禁见
`deploy/tools/verify_log_collect.py` 的 T9-11~T9-13（AST 逐字段结构等价，
不再是字符串存在检查）。

依赖只取 `bastion.0001_initial`（`Credential` 建表就在那里），
不依赖 bastion 后续迁移 —— 本模块只用到 Credential 这一张表。
"""
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
        ('bastion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogCollectTask',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(help_text='如 myapp-prod 应用日志', max_length=64, verbose_name='任务名称')),
                ('index_prefix', models.CharField(help_text='如 myapp（小写字母数字开头）；检索时用 myapp-* 通配', max_length=64, verbose_name='索引前缀')),
                ('collect_mode', models.CharField(choices=[('filebeat', '托管 filebeat 配置片段')], default='filebeat', help_text='当前仅支持托管 filebeat 配置片段', max_length=20, verbose_name='采集方式')),
                ('path_pattern', models.CharField(help_text='绝对路径，支持通配，如 /var/log/myapp/*.log', max_length=255, verbose_name='日志路径')),
                ('include_regex', models.CharField(blank=True, help_text='只采集匹配该正则的行；留空表示不限制', max_length=255, null=True, verbose_name='包含规则(正则)')),
                ('exclude_regex', models.CharField(blank=True, help_text='丢弃匹配该正则的行，优先级高于包含规则', max_length=255, null=True, verbose_name='排除规则(正则)')),
                ('min_level', models.CharField(choices=[('', '不限（全部采集）'), ('debug', 'DEBUG 及以上'), ('info', 'INFO 及以上'), ('warn', 'WARN 及以上'), ('error', 'ERROR 及以上')], default='', help_text='低于该级别的日志直接丢弃', max_length=20, verbose_name='最低级别')),
                ('multiline_start', models.CharField(blank=True, help_text='如 ^\\d{4}-\\d{2}-\\d{2}：堆栈/换行会被并进上一条', max_length=255, null=True, verbose_name='多行起始正则')),
                ('time_regex', models.CharField(blank=True, help_text='含命名组 log_time，如 ^(?P<log_time>\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2})', max_length=255, null=True, verbose_name='时间提取正则')),
                ('time_layout', models.CharField(blank=True, help_text='Go 时间布局，如 2006-01-02 15:04:05', max_length=64, null=True, verbose_name='时间格式')),
                # ★ 2026-09-24：help_text 原文举例写了 {"service":"myapp",...} ——
                #   而 service 是 ECS 的**对象型**顶层字段，照抄它会让 ES 以 HTTP 400
                #   拒收每一条日志（filebeat 静默丢弃）。示例本身就是坑，已改。
                #   help_text 不落库（Django 只在表单/文档层使用），因此在已应用过的
                #   环境里就地改这条不影响任何 schema，也不会产生迁移漂移。
                ('extra_fields', models.JSONField(blank=True, default=dict, help_text='JSON 对象，随每条日志写入。键请用自定义名（如 app_name / env_name）；不要用 service、host、agent、log 等 ECS 名，ES 会以 HTTP 400 拒收每一条日志', verbose_name='附加字段')),
                ('targets', models.JSONField(blank=True, default=list, help_text='JSON 数组：[{"server_id":1,"label":"web-1","ip":"x.x.x.x","ssh_port":22}]', verbose_name='目标服务器')),
                ('remote_dir', models.CharField(default='/etc/filebeat/inputs.d', help_text='目标机上 filebeat 加载配置片段的目录', max_length=255, verbose_name='片段目录')),
                ('status', models.IntegerField(choices=[(1, '启用'), (0, '停用')], default=1, help_text='状态', verbose_name='状态')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('run_status', models.CharField(choices=[('pending', '未下发'), ('applied', '已下发'), ('failed', '下发失败'), ('stopped', '已停止')], default='pending', help_text='目标机上的落地状态', max_length=20, verbose_name='下发状态')),
                ('last_action_at', models.DateTimeField(blank=True, help_text='最近一次下发/停止的时间', null=True, verbose_name='最近操作时间')),
                ('last_message', models.CharField(blank=True, help_text='最近一次操作的摘要（成功或失败原因）', max_length=512, null=True, verbose_name='最近结果')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('credential', models.ForeignKey(blank=True, db_constraint=False, help_text='连接目标机用的统一凭据（复用堡垒机凭据，已加密）', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bastion.credential', verbose_name='凭据')),
                ('source', models.ForeignKey(blank=True, db_constraint=False, help_text='用于「环境检测」比对与跳转检索；落库目标由目标机 filebeat 的 output 决定', null=True, on_delete=django.db.models.deletion.SET_NULL, to='log.elasticsearchsource', verbose_name='ES 数据源')),
            ],
            options={
                'verbose_name': '日志采集任务',
                'verbose_name_plural': '日志采集任务',
                'db_table': 'log_collect_task',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='LogCollectRecord',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('action', models.CharField(choices=[('detect', '环境检测'), ('apply', '下发配置'), ('stop', '停止采集'), ('preview', '规则试跑')], help_text='操作类型', max_length=20, verbose_name='操作')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], help_text='成功 / 失败', max_length=20, verbose_name='结果')),
                ('target_label', models.CharField(blank=True, help_text='命中的目标机（多台时逐台记一行）', max_length=128, null=True, verbose_name='目标')),
                ('ip', models.CharField(blank=True, help_text='目标IP', max_length=64, null=True, verbose_name='目标IP')),
                ('message', models.CharField(blank=True, help_text='结果摘要', max_length=512, null=True, verbose_name='摘要')),
                ('detail', models.TextField(blank=True, help_text='生成的配置片段 / 命令输出 / 错误堆栈', null=True, verbose_name='详情')),
                ('duration', models.FloatField(blank=True, help_text='操作耗时', null=True, verbose_name='耗时(秒)')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('task', models.ForeignKey(db_constraint=False, help_text='所属采集任务', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='log.logcollecttask', verbose_name='采集任务')),
            ],
            options={
                'verbose_name': '日志采集台账',
                'verbose_name_plural': '日志采集台账',
                'db_table': 'log_collect_record',
                'ordering': ['-create_datetime'],
            },
        ),
    ]
