# Generated by XwOps on 2026-09-23
"""日志采集任务：新增 ``tail_new_only``（只采新增）

★ 手写迁移（离线环境没有可用的 Django 来 makemigrations），
  字段与 ``log/models.py`` 逐条对齐；两边不一致时以 models.py 为准。

为什么必须有这个字段
--------------------
filebeat 默认会把路径下**已经存在**的日志从头读一遍。用户拍板的是
「只采新增日志」（接入时不把历史日志灌进 ES），这件事**必须显式落地**：

  · ``log`` input  → ``tail_files: true``（filebeat 官方选项，能真正保证）
  · ``filestream`` → **无**等价项（``ignore_older`` / ``ignore_inactive`` 只对
    「最后修改时间早于阈值」的冷文件生效，持续写入的活跃日志 mtime 一直在变，
    判定恒为「不忽略」⇒ 仍从头读）→ 平台降级用 log input 承载

详见 ``log/collector.py`` 模块 docstring 第 6 条与 ``render_tail_note()``。
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_logcollecttask_logcollectrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcollecttask',
            name='tail_new_only',
            field=models.BooleanField(
                default=True,
                help_text='首次接入时从文件末尾开始，不把已有历史日志灌进 ES',
                verbose_name='只采新增',
            ),
        ),
    ]
