# Generated by Django 4.2.14 on 2026-09-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prometheussource',
            options={'ordering': ['sort', '-create_datetime'], 'verbose_name': '监控数据源', 'verbose_name_plural': '监控数据源'},
        ),
        migrations.AddField(
            model_name='prometheussource',
            name='source_type',
            field=models.CharField(choices=[('prometheus', 'Prometheus'), ('alertmanager', 'Alertmanager')], default='prometheus', help_text='数据类型：Prometheus / Alertmanager', max_length=16, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='prometheussource',
            name='url',
            field=models.CharField(help_text='如 http://192.168.1.100:9090', max_length=255, verbose_name='监控地址'),
        ),
    ]
