# Generated by XwOps on 2026-10-01
"""发布流水线：Pipeline / PipelineNode / PipelineRun / PipelineNodeRun

★ 手写迁移（离线环境没有可用的 Django 来 makemigrations），
  字段与 `release/models.py` 逐条对齐；两边不一致时以 models.py 为准，
  目标机执行 `makemigrations --check --dry-run` 应当**无待生成变更**。

★★ 手写这类迁移时最容易漏的：**继承来的字段也要抄**
-----------------------------------------------------
`CoreModel` 是 **abstract** 基类，Django 会把它的字段**展平**进每个子模型的
`CreateModel.fields` 里 —— 子模型一个字没写，迁移里也必须有。
本模块四个模型都**没有**显式重写 `description`，所以它按 CoreModel 原样抄：
`CharField(max_length=255, verbose_name="描述", null=True, blank=True, help_text="描述")`
（同款坑 2026-09-24 在 `log` 模块踩过：漏了 `description` ⇒
 `makemigrations --check` 报 Add field ⇒ 那一关过不去就 migrate 不了。）

依赖只取 `bastion.0001_initial`（`Credential` 建表就在那里）+
`bastion.0005`（本批给 `CommandLog.source` 加 'release' 那一档）。
"""
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bastion', '0005_alter_commandlog_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('name', models.CharField(help_text='如 myapp 生产发布', max_length=64, verbose_name='流水线名称')),
                ('status', models.IntegerField(choices=[(1, '启用'), (0, '停用')], default=1, help_text='状态', verbose_name='状态')),
                ('params', models.JSONField(blank=True, default=list, help_text='JSON 数组：[{"key":"version","label":"版本号","default":"","required":true}]', verbose_name='运行时参数')),
                ('credential', models.ForeignKey(blank=True, db_constraint=False, help_text='连接目标机的默认凭据（节点可覆盖）；复用堡垒机凭据，已加密', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bastion.credential', verbose_name='默认凭据')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '发布流水线',
                'verbose_name_plural': '发布流水线',
                'db_table': 'release_pipeline',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='PipelineNode',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('name', models.CharField(help_text='如 上传制品 / 重启服务', max_length=64, verbose_name='节点名称')),
                ('node_type', models.CharField(choices=[('param', '参数化'), ('command', '执行命令'), ('check', '环境检查'), ('upload', '上传制品'), ('build', '构建'), ('notify', '通知')], default='command', help_text='节点类型', max_length=20, verbose_name='节点类型')),
                ('config', models.JSONField(blank=True, default=dict, help_text='各类型自己的配置，见 models.py 的字段说明', verbose_name='节点配置')),
                ('seq', models.IntegerField(default=0, help_text='编排顺序（由小到大执行）', verbose_name='顺序号')),
                ('on_failure', models.CharField(choices=[('stop', '失败即停止'), ('continue', '失败继续')], default='stop', help_text='该节点失败后：停止整条流水线 / 继续下一个节点', max_length=20, verbose_name='失败处理')),
                ('pos_x', models.IntegerField(default=0, help_text='预留：自由画布坐标', verbose_name='画布X')),
                ('pos_y', models.IntegerField(default=0, help_text='预留：自由画布坐标', verbose_name='画布Y')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('pipeline', models.ForeignKey(db_constraint=False, help_text='所属流水线', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='release.pipeline', verbose_name='流水线')),
            ],
            options={
                'verbose_name': '流水线节点',
                'verbose_name_plural': '流水线节点',
                'db_table': 'release_pipeline_node',
                'ordering': ['seq', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('pipeline_name', models.CharField(blank=True, help_text='发起时的名称快照', max_length=64, null=True, verbose_name='流水线名称')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '全部成功'), ('partial', '部分失败'), ('failed', '失败'), ('aborted', '已中止')], default='pending', help_text='执行状态', max_length=20, verbose_name='状态')),
                ('params', models.JSONField(blank=True, default=dict, help_text='本次执行实际填入的参数值', verbose_name='本次参数')),
                ('trigger_type', models.CharField(choices=[('manual', '手动触发'), ('schedule', '定时触发')], default='manual', help_text='触发方式', max_length=20, verbose_name='触发方式')),
                ('total_nodes', models.IntegerField(default=0, help_text='节点总数', verbose_name='节点总数')),
                ('done_nodes', models.IntegerField(default=0, help_text='已结束（成功或失败）的节点数', verbose_name='已完成节点')),
                ('failed_nodes', models.IntegerField(default=0, help_text='失败的节点数', verbose_name='失败节点')),
                ('current_node_id', models.IntegerField(blank=True, help_text='正在执行/最近执行的节点 id', null=True, verbose_name='当前节点ID')),
                ('started_at', models.DateTimeField(blank=True, help_text='开始时间', null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, help_text='结束时间', null=True, verbose_name='结束时间')),
                ('last_error', models.TextField(blank=True, help_text='失败节点的错误摘要', null=True, verbose_name='最近错误')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('pipeline', models.ForeignKey(blank=True, db_constraint=False, help_text='所属流水线（可能已被删除）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='release.pipeline', verbose_name='流水线')),
            ],
            options={
                'verbose_name': '流水线执行',
                'verbose_name_plural': '流水线执行',
                'db_table': 'release_pipeline_run',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='PipelineNodeRun',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('node_name', models.CharField(blank=True, help_text='节点名称快照', max_length=64, null=True, verbose_name='节点名称')),
                ('node_type', models.CharField(choices=[('param', '参数化'), ('command', '执行命令'), ('check', '环境检查'), ('upload', '上传制品'), ('build', '构建'), ('notify', '通知')], default='command', help_text='节点类型快照', max_length=20, verbose_name='节点类型')),
                ('seq', models.IntegerField(default=0, help_text='执行顺序', verbose_name='顺序号')),
                ('on_failure', models.CharField(choices=[('stop', '失败即停止'), ('continue', '失败继续')], default='stop', help_text='失败处理快照', max_length=20, verbose_name='失败处理')),
                ('config', models.JSONField(blank=True, default=dict, help_text='发起时固化的节点配置', verbose_name='节点配置快照')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='pending', help_text='节点状态', max_length=20, verbose_name='状态')),
                ('targets_result', models.JSONField(blank=True, default=list, help_text='JSON 数组：[{"label":..,"ip":..,"ok":..,"stdout":..,"exit_code":..}]', verbose_name='逐台结果')),
                ('message', models.CharField(blank=True, help_text='成功或失败的摘要', max_length=512, null=True, verbose_name='结果摘要')),
                ('started_at', models.DateTimeField(blank=True, help_text='开始时间', null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, help_text='结束时间', null=True, verbose_name='结束时间')),
                ('duration', models.FloatField(blank=True, help_text='耗时（秒）', null=True, verbose_name='耗时(秒)')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('node', models.ForeignKey(blank=True, db_constraint=False, help_text='对应节点（可能已被删除）', null=True, on_delete=django.db.models.deletion.SET_NULL, to='release.pipelinenode', verbose_name='节点')),
                ('run', models.ForeignKey(db_constraint=False, help_text='所属执行记录', on_delete=django.db.models.deletion.CASCADE, related_name='node_runs', to='release.pipelinerun', verbose_name='执行记录')),
            ],
            options={
                'verbose_name': '流水线节点执行',
                'verbose_name_plural': '流水线节点执行',
                'db_table': 'release_pipeline_node_run',
                'ordering': ['seq', 'id'],
            },
        ),
    ]
